version: '1.0'

services:
  mysql:
    image: mysql:8
    container_name: mysql-jdbc-connector
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task-management-proj
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: